apiVersion: v1
kind: PersistentVolume
metadata:
  name: rc-local-pv3
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage3
  local:
    path: /Users/javierrico/Applications/docker-desktop-k8-vcs/rc-data-pv3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop